# Site settings
title: thirty-four
email: blog@posnick.org
description: "thirty-four is crafted with love in Brooklyn, by Jeff Posnick."
baseurl: ""
url: "https://jeffy.info"
twitter_username: jeffposnick
github_username:  jeffposnick

# Build settings
markdown: kramdown
exclude: ["node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "package.json", "README.md", "src"]
